# Copyright 2022 Goldman Sachs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Docker

on:
  schedule:
    - cron: "0 0 * * 2" # every Tuesday on default/base branch
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  release:
    name: Run Image Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - parent: legend-engine-config/legend-engine-server
            name: legend-engine-server-http-server

          - parent: legend-engine-xts-sql
            name: legend-engine-xt-sql-postgres-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate tarball from image
        run: |
          docker pull finos/${{ matrix.module.name }}:snapshot
          docker save -o /github/workspace/vuln-image.tar finos/${{ matrix.module.name }}:snapshot

      - name: Scan image for security issues
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scanners: vuln,secret,misconfig,license
          input: /github/workspace/vuln-image.tar
          format: table
          exit-code: 1
          # Ignore unpatched/unfixed vulnerabilities/CVEs
          ignore-unfixed: true
          severity: CRITICAL
          # Manually increase timeout as the default 2-minute is not enough
          # See https://github.com/aquasecurity/trivy/issues/802
          timeout: 10m
